---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webservers on ubuntu16
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  - name: start webserver
    service:
     name: apache2
     state: started
    when: ansible_os_family =="Debian"
  - name: copy index.j2 file into anisble node side 
    template:
      src:
      dest: /var/www/html/index.html


    

